version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: teamvitality-postgres-local
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=teamvitality_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
