packages:
  - api-gateway
  - web-application
  - packages/*
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - protobufjs
  - unrs-resolver
