runtime: custom
env: flex
service: web-app

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3 # For demo purposes
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6

# Add any environment variables your app might need, App Engine provides PORT
env_variables:
  NODE_ENV: 'production'
