name: Deploy Next.js to Firebase Hosting

on:
  push:
    branches:
      - main # Or your deployment branch, e.g., master, prod
    paths:
      - 'web-application/**' # Trigger only if changes are in the web-application directory
  workflow_dispatch: # Allows manual triggering

jobs:
  build_and_deploy_hosting:
    name: Build and Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation

    defaults:
      run:
        working-directory: ./web-application # Set default working directory for all run steps

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2' # Use latest major version
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your Next.js compatible Node version
          cache: 'npm' # Or yarn, pnpm
          cache-dependency-path: web-application/package-lock.json # Path to lock file

      - name: Install Dependencies
        run: npm ci # Use ci for cleaner installs in CI

      - name: Build Next.js Application
        run: npm run build # This runs `next build` as defined in your package.json

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0 # Use official Firebase action
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}' # For GitHub deployment statuses
          channelId: live # Deploy to the live channel (or use 'preview' for PRs)
          projectId: '${{ secrets.GCP_PROJECT_ID }}'
          target: hosting # Specify deploying to hosting
          entryPoint: ./web-application # Specifies the root of your Firebase project for the deploy action
                                      # This helps the action find firebase.json correctly.
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks # Enable framework-aware CLI features