name: Deploy Web Application

on:
  push:
    branches:
      - main # Or your primary development branch
    paths:
      - 'web-application/**'
      - '.github/workflows/deploy-web-application.yml' # To redeploy if workflow changes
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # For Workload Identity Federation

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}' # projects/YOUR_GCP_PROJECT_NUMBER/locations/global/workloadIdentityPools/YOUR_POOL_ID/providers/YOUR_PROVIDER_ID
        service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}' # YOUR_GCP_SERVICE_ACCOUNT_EMAIL

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy to App Engine
      run: gcloud app deploy web-application/app.yaml --project=${{ secrets.GCP_PROJECT_ID }} --quiet
